% DATA FOLDERS FOR ANALYSE ORGANIZED BY SESSIONS
% M-BLU_Day2_16x4 session excluded
% Re-written by Pierre Varichon 2024 to link with the new data structure
% Old register can be found in "data_folders_excl_legacy"

function sessions = data_folders_excl

    sessions = [{'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\M-BLU_16x8'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\N-BLU_16x8'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\P-ORA_16x8'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\Q-BLU_16x8'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\N-BLU_16x4'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\P-ORA_16x4'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\Q-BLU_16x4'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\M-BLU_16x3'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\N-BLU_16x3'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\P-ORA_16x3'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\Q-BLU_16x3'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\M-BLU_16x2'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\N-BLU_16x2'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\P-ORA_16x2'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\Q-BLU_16x2'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\M-BLU_16x1'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\N-BLU_16x1'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\P-ORA_16x1'},...
        {'Z:\BendorLab\experimental_data\HIPP\Representational_drift_and_replay_analysis\ExpData\Q-BLU_16x1'}];

end
