% DATA FOLDERS FOR ANALYSE ORGANIZED BY SESSIONS

function sessions = data_folders_GPU

% 16x8
      sessions.S16_8 = [{'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\M-BLU\M-BLU_Day4_16x8'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\N-BLU\N-BLU_Day2_16x8'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\P-ORA\P-ORA_Day5_16x8'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\Q-BLU\Q-BLU_Day8_16x8'}];

% 16x4
     sessions.S16_4= [{'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\M-BLU\M-BLU_Day2_16x4'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\N-BLU\N-BLU_Day5_16x4'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\P-ORA\P-ORA_Day4_16x4'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\Q-BLU\Q-BLU_Day5_16x4'}];
    
    
% 16x3
    sessions.S16_3 = [{'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\M-BLU\M-BLU_Day6_16x3'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\N-BLU\N-BLU_Day4_16x3'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\P-ORA\P-ORA_Day2_16x3'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\Q-BLU\Q-BLU_Day6_16x3'}];

% 16x2
    sessions.S16_2 = [{'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\M-BLU\M-BLU_Day5_16x2'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\N-BLU\N-BLU_Day1_16x2'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\P-ORA\P-ORA_Day3_16x2'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\Q-BLU\Q-BLU_Day4_16x2'}];
% 16x1
     sessions.S16_1 = [{'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\M-BLU\M-BLU_Day3_16x1'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\N-BLU\N-BLU_Day3_16x1'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\P-ORA\P-ORA_Day7_16x1'},...
        {'Z:\BendorLab\Drobo\Lab Members\Marta\Analysis\HIPP\Q-BLU\Q-BLU_Day7_16x1'}];

end 
